### ISSUE TITLE
A little help needed!

### ISSUE THREAD

**Issue by skavan** [jensrossbach/node-red-contrib-sony-audio#1]
Hi,
Cool node.
Just a bit stuck on what to input to the controller to cause it to send one of the Filter commands.

i.e. I want to set up some manual triggers that do a:

- Power On, Power Off
- Get Sound Setting (all)
- Get Playback Mode (all)
- Get Source - Zone 1

What would help is a test flow to import...I should be able to deduce how it works from there.

Thanks.

**Comment by jensrossbach** [comment]
Hi,

yes if you want to do this programmatically, you need a change node. I attached an example with your use cases, one time with a dedicated controller node for each and another time with only one controller node and change nodes.

Putting the command directly inside msg made most sense for me to clearly separate the command from its content/arguments (= payload). The command is more like metadata while the arguments are the actual payload.

[issue_1.zip](https://github.com/jensrossbach/node-red-contrib-sony-audio/files/3542218/issue_1.zip)

**Comment by jensrossbach** [comment]
If you want, you can create a feature request issue demanding to also accept a command property within `msg.payload`.

**Comment by jensrossbach** [comment]
@skavan I don't have a STR-1080dn, just a HT-XT3, so I can't test this. From what I can see in the API documentation, `getPlayingContentInfo` might give you at least some information.

**Comment by jensrossbach** [comment]
I decided to implement the feature requested by @skavan above. I will reuse this issue to track the progress.

**Comment by jensrossbach** [comment]
With the idea of supporting `msg.topic` and the ability to provide the command as topic (see issue #3), the implementation as described above will not be necessary anymore. Inject nodes provide the possibility to set the topic of the output message, so no change node would be needed anymore. Therefore I will close this issue.
