### ISSUE TITLE
Flows stopped due to missing node types.

### ISSUE THREAD

**Issue by Geving** [jensrossbach/node-red-contrib-sony-audio#14]
When (re)starting the Node-RED service, I am greeted with a message telling me that "Flows stopped due to missing node types." and then lists "sony-audio-device".

I've tried _npm r node-red-contrib-sony-audio_ followed by a service restart and then _npm install node-red-contrib-sony-audio_ without any success.

I'm running version 1.5.1 of the Sony Audio node.
NPM v6.14.4
node v12.16.2
Node-RED v1.0.5

The configuration nodes sidebar shows "unknown" nodes for every device I add.

**Comment by jensrossbach** [comment]
Hello, do you maybe have logs that you could share?

**Comment by jensrossbach** [comment]
@Geving Any update on this? Do you still have this issue or have you been able to solve it meanwhile?

**Comment by jensrossbach** [comment]
You might try out version 1.5.3, there I fixed a potential crash which occurred upon network problems.

**Comment by jensrossbach** [comment]
Closing because no feedback from submitter.
